CREATE database Insurabrokerage_feesnce_Data;

SELECT * from bridge_table;
SELECT * from brokerage_fees;
SELECT * from income_class_bridge;
SELECT * from individual_budget;
SELECT * from invoice;
SELECT * from meeting_list;
SELECT * from opportunity;

#KPI 1 - NO OF INVOICE BY ACCOUNT EXECUTIVE

SELECT Account_Executive,
sum(CASE WHEN INCOME_CLASS="CROSS SELL" THEN 1 ELSE 0 END) AS CROSS_SELL_COUNT,
SUM(CASE WHEN INCOME_CLASS="NEW" THEN 1 ELSE 0 END) AS NEW_COUNT, 
SUM(CASE WHEN INCOME_CLASS="RENEWAL" THEN 1 ELSE 0 END) AS RENEWAL_COUNT,
SUM(CASE WHEN INCOME_CLASS="" THEN 1 ELSE 0 END) AS NULL_INVOICE_COUNT,
COUNT(INVOICE_NUMBER) AS INVOICE_COUNT
FROM INVOICE
GROUP BY  Account_Executive
ORDER BY INVOICE_COUNT DESC;

#KPI-2 YEARLY MEETING COUNT

SELECT YEAR AS MEETING_YEAR, COUNT(*) AS MEETING_COUNT
FROM meeting_list
group by MEETING_YEAR;

# KPI-4 STAGE FUNNEL BY REVENUE

SELECT STAGE, SUM(REVENUE_AMOUNT) AS REVENUE_AMOUNT
FROM opportunity
group by STAGE
ORDER BY revenue_amount desc;

#KPI-5 NUMBER OF MEETINGS BY ACCOUNT EXECUTIVE

SELECT ACCOUNT_EXECUTIVE, COUNT(*) AS MEETING_COUNT
FROM meeting_list
GROUP BY Account_Executive
ORDER BY MEETING_COUNT desc;

#KPI-6 TOP 5 OPPOTURNITY BY REVENUE

SELECT OPPORTUNITY_NAME, SUM(REVENUE_AMOUNT) AS REVENUE_AMOUNT 
FROM OPPORTUNITY
GROUP BY OPPORTUNITY_NAME 
ORDER BY REVENUE_AMOUNT DESC
LIMIT 5;

#KPI-3
#TARGET,INVOICE,ACHIEVED
#PLACED_ACHIEVED_PERCENTAGE,INVOICED_ACHIEVED_PERCENTAGE BY INCOME_CLASS
#CROSS_SELL,NEW,RENEWAL	

#PROCEDURE
DELIMITER //
CREATE PROCEDURE `DATA_BY_INCOME_CLASS`(IN INCOMECLASS VARCHAR(10))
BEGIN
DECLARE BUDGET_VAL DOUBLE;
# TARGET,INVOICE,ACHIEVED FOR CROSS_SELL,NEW,RENEWAL
SET @CROSS_SELL_TARGET =(SELECT SUM(CROSS_SELL_BUDGET) FROM INDIVIDUAL_BUDGET);
SET @NEW_TARGET =(SELECT SUM(NEW_BUDGET) FROM INDIVIDUAL_BUDGET);
SET @RENEWAL_TARGET =(SELECT SUM(RENEWAL_BUDGET) FROM INDIVIDUAL_BUDGET);

SET @INVOICE_VAL=(SELECT SUM(AMOUNT) FROM INVOICE WHERE INCOME_CLASS=INCOMECLASS);
SET @ACHIEVED_VAL=((SELECT SUM(AMOUNT) FROM BROKERAGE_FEES WHERE INCOME_CLASS=INCOMECLASS) +
					(SELECT SUM(AMOUNT) FROM FEES WHERE INCOME_CLASS=INCOMECLASS));

IF INCOMECLASS="CROSS SELL" THEN SET BUDGET_VAL= @CROSS_SELL_TARGET;
	ELSEIF INCOMECLASS="NEW" THEN SET BUDGET_VAL= @NEW_TARGET;
	ELSEIF INCOMECLASS="RENEWAL" THEN SET BUDGET_VAL= @RENEWAL_TARGET;
	ELSE SET BUDGET_VAL=0;
END IF;

# PERCENTAGE OF PLACED ACHIEVEMENT FOR CROSS SELL,NEW,RENEWAL
SET @PLACED_ACHIVEMENT=(SELECT CONCAT(FORMAT((@ACHIEVED_VAL/@BUDGET_VAL)*100,2),'%'));
# PERCENTAGE OF INVOICE ACHIEVEMENT FOR CROSS SELL,NEW,RENEWAL
SET @INVOICE_ACHIVEMENT=(SELECT CONCAT(FORMAT((@INVOICE_VAL/@BUDGET_VAL)*100,2),'%'));

SELECT INCOMECLASS,FORMAT(BUDGET_VAL,0) AS TARGET, FORMAT(@INVOICE_VAL,0) AS INVOICE,
FORMAT(@ACHIEVED_VAL,2) AS ACHIEVED, @PLACED_ACHIVEMENT AS PLACED_ACHIEVEMENT_PERCENTAGE,
@INVOICE_ACHIVEMENT AS INVOICE_ACHIVEMENT_PERCENTAGE;

END //

CALL DATA_BY_INCOME_CLASS('CROSS SELL');

CALL DATA_BY_INCOME_CLASS('NEW');

CALL DATA_BY_INCOME_CLASS('RENEWAL');

 

